# Generated by Django 4.2.2 on 2023-08-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateTelegramBots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('gmail', 'gmail'), ('azure', 'azure')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.FileField(unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MailServerAuthenticationInfo',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=350, null=True)),
                ('tenant_id', models.CharField(max_length=350)),
                ('client_id', models.CharField(max_length=350)),
                ('secret', models.CharField(max_length=350)),
                ('authority', models.CharField(max_length=350)),
                ('scope', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('bot_name', models.CharField(max_length=50)),
                ('bot_id', models.URLField(max_length=260)),
                ('bot_token', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('group_name', models.CharField(max_length=50)),
                ('group_url', models.URLField(max_length=260)),
                ('group_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LastEmailDateTimeRead',
            fields=[
                ('email_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EmailAutomationBot.email')),
                ('lastemailreaddatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BotGroupEmailUserRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailAutomationBot.telegrambot')),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailAutomationBot.email')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailAutomationBot.telegramgroup')),
                ('mail_server_auth_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailAutomationBot.mailserverauthenticationinfo')),
            ],
        ),
    ]
