# Generated by Django 4.2.2 on 2023-07-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAutomationBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_type',
            field=models.CharField(choices=[('gmail', 'gmail'), ('َazure', 'azure')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LastEmailDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastemailreaddatetime', models.DateTimeField()),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailAutomationBot.email')),
            ],
        ),
    ]
