# Generated by Django 4.2.2 on 2023-08-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAutomationBot', '0002_mailserverauthenticationinfo_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botgroupemailuserrelations',
            old_name='mail_server_auth_info',
            new_name='name',
        ),
    ]
