# Generated by Django 4.2.2 on 2023-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAutomationBot', '0003_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_data',
            field=models.FileField(upload_to=''),
        ),
    ]
