# Generated by Django 4.2.2 on 2023-08-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAutomationBot', '0003_rename_mail_server_auth_info_botgroupemailuserrelations_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botgroupemailuserrelations',
            old_name='name',
            new_name='server_name',
        ),
        migrations.RenameField(
            model_name='mailserverauthenticationinfo',
            old_name='name',
            new_name='server_name',
        ),
    ]
