# Generated by Django 4.2.2 on 2023-07-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAutomationBot', '0004_alter_filemodel_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_data',
            field=models.FileField(unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lastemaildatetime',
            name='email_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmailAutomationBot.email'),
        ),
    ]
