# Generated by Django 4.2.2 on 2023-07-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAutomationBot', '0005_alter_filemodel_file_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastemaildatetime',
            name='id',
        ),
        migrations.AlterField(
            model_name='lastemaildatetime',
            name='email_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='EmailAutomationBot.email'),
        ),
    ]
