# Generated by Django 4.2.2 on 2023-08-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAutomationBot', '0005_activatetelegrambots_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatetelegrambots',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=50),
        ),
    ]
