# Generated by Django 4.2.2 on 2023-07-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailAutomationBot', '0009_remove_lastemaildatetime_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email_addresss',
            new_name='email_address',
        ),
    ]
